#!/bin/bash
## Actualiza el ambiente del primer argumento a partir del segundo argumento
for d in */;
do
	echo -e "\n\n$d"
	cd $d
	LAST_TAG_DEV=`git tag --sort=creatordate | grep $2\_ | tail -1`
	LAST_TAG_TST=`git tag --sort=creatordate | grep $1\_ | tail -1`
	LAST_VERSION_DEV=`echo $LAST_TAG_DEV | cut -d"_" -f 2`
	LAST_VERSION_TST=`echo $LAST_TAG_TST | cut -d"_" -f 2`
	if [[ $LAST_VERSION_DEV = $LAST_VERSION_TST  ]]; 
	then
		echo "Versiones iguales en dev y tst"
	else
		echo "Versión dev: $LAST_VERSION_DEV"
		echo -e "Versión tst: $LAST_VERSION_TST\n"
		TST_TAG="$1_$LAST_VERSION_DEV"
		git checkout $LAST_TAG_DEV
		git tag -a $TST_TAG -m "Versión $LAST_VERSION_DEV"
		git switch -	
#		git push origin $TST_TAG
		git push tfs-gov $TST_TAG
	fi
	cd ..
done
